# Flask config
TESTING = True
SECRET_KEY = "secret"
PERMANENT_SESSION_LIFETIME = 180
JSONIFY_PRETTYPRINT_REGULAR = True
UPLOAD_FOLDER = "/tmp"
ALLOWED_EXTENSIONS = {"csv"}
LOG_FILE = "../sms-log.txt"
